var cosasHogar = [
    {
        tipo: 'Electrodomestico',
        nombre: "Lavadora Samsung",
        precio: 550,
        imagen: "https://cdn.pixabay.com/photo/2016/01/28/22/07/washing-machine-1167053_640.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Refrigerador LG",
        precio: 1200,
        imagen: "https://m.media-amazon.com/images/I/61xtl+JJ+zL._AC_SR278,278_QL70_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Horno Bosch",
        precio: 800,
        imagen: "https://m.media-amazon.com/images/I/813nsQcI21L._AC_UY218_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Aspiradora Dyson",
        precio: 400,
        imagen: "https://cdn.pixabay.com/photo/2015/03/03/18/39/vacuum-cleaner-657719_640.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Licuadora Philips",
        precio: 70,
        imagen: "https://media.istockphoto.com/id/1455417356/es/foto/mujer-mezclando-espinacas-bayas-pl%C3%A1tanos-y-leche-de-almendras-para-hacer-un-batido-verde.jpg?s=612x612&w=is&k=20&c=LwMyMrji0Zcky2Hg2VnQIEVIXNX5Oeo4wzGZC3B0v9k="
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Cafetera Taurus",
        precio: 90,
        imagen: "https://m.media-amazon.com/images/I/51r-kXmr2jL._AC_UL320_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Microondas Panasonic",
        precio: 150,
        imagen: "https://m.media-amazon.com/images/I/61r+y7ENK+L._AC_UY218_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Batidora KitchenAid",
        precio: 300,
        imagen: "https://m.media-amazon.com/images/I/61zues++KxL._AC_UY218_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Plancha Rowenta",
        precio: 50,
        imagen: "https://m.media-amazon.com/images/I/71vUCDj2k5L._AC_UY218_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Tostadora Ufesa",
        precio: 40,
        imagen: "https://m.media-amazon.com/images/I/71nA3eLKqAL._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Mesa de Comedor",
        precio: 300,
        imagen: "https://m.media-amazon.com/images/I/91rLEPwxDPL._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Sofá de Tela",
        precio: 700,
        imagen: "https://m.media-amazon.com/images/I/813tNWo6oFL._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Lámpara de Pie",
        precio: 80,
        imagen: "https://m.media-amazon.com/images/I/41oPb3fMhHL._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Juego de Sábanas",
        precio: 50,
        imagen: "https://m.media-amazon.com/images/I/81h+LmzsF-L._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Set de Ollas",
        precio: 120,
        imagen: "https://m.media-amazon.com/images/I/61HUZ+svb6L._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Silla de Oficina",
        precio: 150,
        imagen: "https://m.media-amazon.com/images/I/71pceWy1DjL._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Cómoda de Dormitorio",
        precio: 250,
        imagen: "https://m.media-amazon.com/images/I/81trKitrz5L._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Estantería Modular",
        precio: 180,
        imagen: "https://m.media-amazon.com/images/I/61ywKo7d51L._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Mesa de Centro",
        precio: 120,
        imagen: "https://m.media-amazon.com/images/I/71RKNT6GbXL._AC_UL320_.jpg"
    },
    {
        tipo: 'Muebles',
        nombre: "Sillón Reclinable",
        precio: 350,
        imagen: "https://m.media-amazon.com/images/I/71cl228h5RL._AC_UL320_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Robot de Cocina",
        precio: 500,
        imagen: "https://m.media-amazon.com/images/I/51DBd7O6GEL._AC_UY218_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Plancha de Vapor",
        precio: 80,
        imagen: "https://m.media-amazon.com/images/I/81c7+-CrSuL._AC_UY218_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Batidora de Mano",
        precio: 60,
        imagen: "https://m.media-amazon.com/images/I/61RE5FyKa2L._AC_UL320_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Cafetera de Cápsulas",
        precio: 150,
        imagen: "https://m.media-amazon.com/images/I/616APtRY0DL._AC_UL320_.jpg"
    },
    {
        tipo: 'Electrodomestico',
        nombre: "Freidora de Aire",
        precio: 200,
        imagen: "https://m.media-amazon.com/images/I/81khOGe1cIL._AC_UY218_.jpg"
    }
];



var accesoriosElectronicos = [
    {
        tipo: "PC",
        nombre: "Monitor Gaming 4K",
        precio: 600,
        imagen: "https://m.media-amazon.com/images/I/61ChqFsekNL._AC_UY218_.jpg"
    },
    {
        tipo: "PC",
        nombre: "Teclado Mecánico RGB",
        precio: 100,
        imagen: "https://m.media-amazon.com/images/I/71T1WQSxp9L._AC_UY218_.jpg"
    },
    {
        tipo: "PC",
        nombre: "Mouse Inalámbrico para Juegos",
        precio: 80,
        imagen: "https://m.media-amazon.com/images/I/61Ibl7dJyUL._AC_UY218_.jpg"
    },
    {
        tipo: "PC",
        nombre: "Silla Gamer Ergonómica",
        precio: 250,
        imagen: "https://m.media-amazon.com/images/I/71wTMO+iQIL._AC_UL320_.jpg"
    },
    {
        tipo: "PC",
        nombre: "Laptop Gaming de Alta Gama",
        precio: 1500,
        imagen: "https://m.media-amazon.com/images/I/71a2UNJn18L._AC_UY218_.jpg"
    },
    {
        tipo: "PC",
        nombre: "Mochila para Laptop",
        precio: 50,
        imagen: "https://m.media-amazon.com/images/I/717Rp03xdmL._AC_UY218_.jpg"
    },
    {
        tipo: "Juegos",
        nombre: "Controlador Inalámbrico para Consola",
        precio: 60,
        imagen: "https://m.media-amazon.com/images/I/613ZxWuyG8L._AC_UY218_.jpg"
    },
    {
        tipo: "Juegos",
        nombre: "Auriculares Gaming con Sonido Envolvente",
        precio: 120,
        imagen: "https://m.media-amazon.com/images/I/51FRJHB7XOL._AC_UY218_.jpg"
    },
    {
        tipo: "Móviles",
        nombre: "Smartphone de Última Generación",
        precio: 800,
        imagen: "https://i.pinimg.com/236x/5b/55/02/5b5502e7b4051c612a44686297d8a90d.jpg"
    },
    {
        tipo: "Móviles",
        nombre: "Funda Protectora con Carga Inalámbrica",
        precio: 40,
        imagen: "https://i.pinimg.com/236x/f8/ab/97/f8ab97497f640cc7df81824d89e29ee5.jpg"
    },
    {
        tipo: "Accesorios",
        nombre: "Batería Externa de Gran Capacidad",
        precio: 70,
        imagen: "https://i.pinimg.com/236x/b7/6d/d1/b76dd1188d4edd116306d8a3a7ac3fed.jpg"
    },
    {
        tipo: "Accesorios",
        nombre: "Soporte Ajustable para Teléfono",
        precio: 20,
        imagen: "https://i.pinimg.com/236x/13/53/12/1353125463574d61b412169b163f626c.jpg"
    },
    {
        tipo: "PC",
        nombre: "Monitor Curvo Ultrawide",
        precio: 800,
        imagen: "https://m.media-amazon.com/images/I/71tZjjI5GKL._AC_UY218_.jpg"
    },
    {
        tipo: "PC",
        nombre: "Auriculares Inalámbricos para Gaming",
        precio: 150,
        imagen: "https://m.media-amazon.com/images/I/711mxbCzvdL._AC_UY218_.jpg"
    },
    {
        tipo: "PC",
        nombre: "Micrófono Profesional USB",
        precio: 120,
        imagen: "https://m.media-amazon.com/images/I/71MF4JRZKmL._AC_UL320_.jpg"
    },
    {
        tipo: "PC",
        nombre: "Alfombrilla de Ratón RGB",
        precio: 40,
        imagen: "https://m.media-amazon.com/images/I/81oE1XMLAwL._AC_UL320_.jpg"
    },
    {
        tipo: "PC",
        nombre: "Silla Ergonómica con Masajeador",
        precio: 350,
        imagen: "https://m.media-amazon.com/images/I/71yTKI05CLL._AC_UL320_.jpg"
    },
    {
        tipo: "Móviles",
        nombre: "Cargador Inalámbrico de Carga Rápida",
        precio: 30,
        imagen: "https://m.media-amazon.com/images/I/71Fvzpb557L._AC_UY218_.jpg"
    },
    {
        tipo: "Móviles",
        nombre: "Soporte para Coche con Carga Inalámbrica",
        precio: 50,
        imagen: "https://m.media-amazon.com/images/I/616ScZGEw5L._AC_UL320_.jpg"
    },
    {
        tipo: "Móviles",
        nombre: "Auriculares Bluetooth Deportivos",
        precio: 60,
        imagen: "https://m.media-amazon.com/images/I/71e2GCgJnyL._AC_UY218_.jpg"
    },
    {
        tipo: "Móviles",
        nombre: "Funda Resistente para Smartphone",
        precio: 25,
        imagen: "https://m.media-amazon.com/images/I/71Dfmp6z2SL._AC_UY218_.jpg"
    },
    {
        tipo: "Móviles",
        nombre: "Palillo de Selfie Extensible",
        precio: 15,
        imagen: "https://m.media-amazon.com/images/I/61sSegdaHhL._AC_UY218_.jpg"
    },
    {
        tipo: "Accesorios",
        nombre: "Cable USB-C a HDMI",
        precio: 20,
        imagen: "https://m.media-amazon.com/images/I/81H9vhAoTUL._AC_UL320_.jpg"
    },
    {
        tipo: "Accesorios",
        nombre: "Base de Carga Múltiple para Dispositivos",
        precio: 70,
        imagen: "https://m.media-amazon.com/images/I/71Wm8bzk5jL._AC_UY218_.jpg"
    },
    {
        tipo: "Accesorios",
        nombre: "Estuche Impermeable para Electrónicos",
        precio: 35,
        imagen: "https://m.media-amazon.com/images/I/81AakTtIygL._AC_UY218_.jpg"
    },
    {
        tipo: "Accesorios",
        nombre: "Adaptador de Enchufe Universal",
        precio: 15,
        imagen: "https://m.media-amazon.com/images/I/612dwAzD56L._AC_UL320_.jpg"
    },
    {
        tipo: "Accesorios",
        nombre: "Soporte Ajustable para Tablet",
        precio: 25,
        imagen: "https://m.media-amazon.com/images/I/617238v7yQL._AC_UY218_.jpg"
    }
];


  var prendasHombre = [
    {
        tipo: "Hombre",
        nombre: "Traje de Vestir",
        precio: 500,
        imagen: "https://i.pinimg.com/236x/a2/58/12/a2581294b554aff453c7d7b46342ca52.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Camisa de Vestir",
        precio: 80,
        imagen: "https://i.pinimg.com/236x/34/ba/b7/34bab7c4837d2f2de2950c7deac0fb93.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Pantalón de Vestir",
        precio: 120,
        imagen: "https://i.pinimg.com/236x/52/91/5b/52915b155203853d955a7d451d7f8646.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Chaqueta de Cuero",
        precio: 250,
        imagen: "https://i.pinimg.com/236x/c6/76/90/c676909797403a6fceefb8f127f335aa.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Corbata de Seda",
        precio: 50,
        imagen: "https://i.pinimg.com/236x/3a/4a/fd/3a4afdb11ac300837305eb03a05046a1.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Suéter de Cuello Alto",
        precio: 150,
        imagen: "https://i.pinimg.com/236x/b1/bd/1c/b1bd1c17f50a60965b74484c851dfc45.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Pantalones Vaqueros Slim Fit",
        precio: 80,
        imagen: "https://i.pinimg.com/236x/0a/43/65/0a43655bf5436d589d8604ed1817e775.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Zapatos Formales de Cuero",
        precio: 200,
        imagen: "https://i.pinimg.com/236x/2d/fd/09/2dfd0962c41612c0d0301fff08e3a486.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Camiseta Polo",
        precio: 50,
        imagen: "https://i.pinimg.com/236x/92/8d/8a/928d8a1adefeffecc0f9e9c68d2589a8.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Chaqueta Impermeable",
        precio: 120,
        imagen: "https://i.pinimg.com/236x/0e/0e/9a/0e0e9ab3a9dc690a6acfb146c9ed231f.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Abrigo de Lana",
        precio: 300,
        imagen: "https://i.pinimg.com/236x/9c/fb/14/9cfb142ee8487e76da514b7aaa94bde2.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Bufanda de Algodón",
        precio: 40,
        imagen: "https://i.pinimg.com/236x/de/51/59/de5159c0029d3f11e2d6f6522f9f9d9b.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Gorra de Cuero",
        precio: 60,
        imagen: "https://i.pinimg.com/236x/41/a1/ab/41a1abfe0f41a7c5dea1828130f50075.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Chaleco Acolchado",
        precio: 120,
        imagen: "https://i.pinimg.com/236x/4b/34/91/4b34918ece314a17d17b8415aa35cd54.jpg"
    },
    {
        tipo: "Hombre",
        nombre: "Pantalones Cargo",
        precio: 90,
        imagen: "https://i.pinimg.com/236x/4e/29/e8/4e29e8acfea1ba6b39032bc5cd340291.jpg"
    },
    // Puedes seguir añadiendo más prendas para hombre según tus necesidades
];
  
var prendasMujer = [
    {
        tipo: "Mujer",
        nombre: "Abrigo de Plumón",
        precio: 250,
        imagen: "https://i.pinimg.com/236x/f7/8e/e9/f78ee9f4420f78fd1be0a674e745e61b.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Pantalones de Cuero",
        precio: 120,
        imagen: "https://i.pinimg.com/236x/bd/33/4a/bd334ae767b2315ae1c51b2e99272799.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Botines de Tacón Alto",
        precio: 180,
        imagen: "https://i.pinimg.com/236x/f7/5a/f5/f75af5c90f741f09bb056259e0c6b8c8.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Blazer Elegante",
        precio: 180,
        imagen: "https://i.pinimg.com/236x/5d/7d/ee/5d7deeffa2d06d17ec40e321c90921d5.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Vestido Casual de Verano",
        precio: 70,
        imagen: "https://i.pinimg.com/236x/a7/9e/e6/a79ee6c7ee9d092ab03070066b566d01.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Vestido de Noche",
        precio: 600,
        imagen: "https://i.pinimg.com/236x/2d/63/1b/2d631b5c732099b48cdd83204d9668fc.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Blusa Elegante",
        precio: 90,
        imagen: "https://i.pinimg.com/236x/8b/8c/10/8b8c10458ddc5f391d76bd81615f1716.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Falda Midi",
        precio: 100,
        imagen: "https://i.pinimg.com/236x/95/72/e0/9572e0804515edf075e0fe14dfd5d61f.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Abrigo de Lana",
        precio: 300,
        imagen: "https://i.pinimg.com/236x/32/e0/de/32e0de856d69ffd68e4e4c7084c397bb.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Bufanda de Seda",
        precio: 40,
        imagen: "https://i.pinimg.com/236x/37/66/73/37667385eb30523c5d0d341e786ceff3.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Chaqueta de Cuero",
        precio: 200,
        imagen: "https://i.pinimg.com/236x/13/38/f5/1338f5807af5e35a4ce7f8076076736c.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Sweater de Punto",
        precio: 80,
        imagen: "https://i.pinimg.com/236x/22/31/0e/22310e6ee6e691810a5d37a2b980d56e.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Zapatos de Tacón Clásicos",
        precio: 150,
        imagen: "https://i.pinimg.com/236x/fc/0c/27/fc0c27a4a134f4a8510463cddcba8ce9.jpg"
    },
    {
        tipo: "Mujer",
        nombre: "Blusa Estampada",
        precio: 35,
        imagen: "https://i.pinimg.com/236x/be/fd/90/befd90b71f60991fcb181a74e21784af.jpg"
    }
    // Puedes seguir añadiendo más prendas para mujer según tus necesidades
];

const productosHogar = document.querySelector('.zoneHogar');
const productosElectronico = document.querySelector('.zoneElectronico');
const productosHombre =document.querySelector('.zone-caballero');
const productosMujer =document.querySelector('.zone-dama');
const inputBusqueda = document.getElementById('inputBusqueda');
const card = document.querySelector('.card');
const hogar = document.querySelector('#hogar');
const electronico = document.querySelector('#electronico');
const ropa = document.querySelector('#ropa');
const resultad = document.querySelector('.resultado');
const navLateral = document.querySelector('.nav-lateral');
const tienda = document.querySelector('.tienda')
const tablecarrito = document.querySelector('#list-carrito');
const tbcarrito = document.querySelector('#list-carrito tbody');
const vaciarCarrito = document.querySelector('#vaciar')
const pagar = document.querySelector('#pagar');
const zonePagar = document.querySelector('.pagar');
let articulosCarrito = [];
let numer = 0; // Inicializamos la variable

function crearCardHTML(producto) {
    const { nombre, precio, imagen } = producto;
    return `
      <div class="card">
        <img src="${imagen}" id="imgCard" alt="Descripción de la imagen">
        <div class="contenido-card">
          <div class="medida-responsive">
            <h3>${nombre}</h3>
            <p>Precio: $ <span class="precio">${precio}</span></p>
          </div>
          <div class="btn-responsive">
            <img class="agregar" src="img/carrito de compras.png" title="agregar a carrito" >
            <button class="ver">Ver</button>
          </div>
        </div>
      </div>
    `;
}

function mostrarCosas(cosasHogar) {
    cosasHogar.forEach(hogar => {
        const cardHTML = crearCardHTML(hogar);
        productosHogar.insertAdjacentHTML('beforeend', cardHTML);
    });
}

mostrarCosas(cosasHogar);

function mostrarElectronicos(accesoriosElectronicos) {
    accesoriosElectronicos.forEach(electronico => {
        const cardHTML = crearCardHTML(electronico);
        productosElectronico.insertAdjacentHTML('beforeend', cardHTML);
    });
}

mostrarElectronicos(accesoriosElectronicos);

function mostrarRopaCaballero(prendasHombre) {
    prendasHombre.forEach(ropaHombre => {
        const cardHTML = crearCardHTML(ropaHombre);
        productosHombre.insertAdjacentHTML('beforeend', cardHTML);        
    })
};

mostrarRopaCaballero(prendasHombre)

function mostrarRopaDama(prendasMujer) {
    prendasMujer.forEach(ropaMujer => {
        const cardHTML = crearCardHTML(ropaMujer);
        productosMujer.insertAdjacentHTML('beforeend', cardHTML);        
    })
}

mostrarRopaDama(prendasMujer)

const todosLosProductos = [
    ...cosasHogar,
    ...accesoriosElectronicos,
    ...prendasHombre,
    ...prendasMujer
];
  
const nombresArrays = [
    ...new Set([
      ...cosasHogar.map(({ nombre }) => nombre),
      ...accesoriosElectronicos.map(({ nombre }) => nombre),
      ...prendasHombre.map(({ nombre }) => nombre),
      ...prendasMujer.map(({ nombre }) => nombre)
    ])
];
  
inputBusqueda.addEventListener('keyup', e => {
    const textoIngresado = e.target.value.toLowerCase();
    const nombresCoincidentes = nombresArrays.filter(nombre => nombre.toLowerCase().includes(textoIngresado));
  
    const resultadosBusqueda = document.querySelector('#resultadosBusqueda');
    resultadosBusqueda.innerHTML = ''; // Limpiar los resultados anteriores
  
    if (textoIngresado === ''){
        resultad.style.display = 'none';
        hogar.style.display = 'flex';
        electronico.style.display = 'flex';
        ropa.style.display = 'flex';
    } else if(textoIngresado.length > 0){
        nombresCoincidentes.forEach(nombre => {
        const productoEncontrado = todosLosProductos.find(producto => producto.nombre.toLowerCase() === nombre.toLowerCase());
        if (productoEncontrado) {
            const { nombre, precio, imagen } = productoEncontrado;
            const cardHTML = `
                <div class="card">
                <img src="${imagen}" id="imgCard" alt="Descripción de la imagen">
                <div class="contenido-card">
                    <div class="medida-responsive">
                    <h3>${nombre}</h3>
                    <p>Precio: $ <span class="precio">${precio}</span></p>
                    </div>
                    <div class="btn-responsive">
                    <img class="agregar" src="img/carrito de compras.png" title="agregar a carrito" >
                    <button class="ver">Ver</button>
                    </div>
                </div>
                </div>
            `;
            resultad.style.display = 'flex';
            hogar.style.display = 'none';
            electronico.style.display = 'none';
            ropa.style.display = 'none';
    
            resultadosBusqueda.insertAdjacentHTML('beforeend', cardHTML); 
        } 
    });
    }
});

const tipoArrays = [
    ...new Set([
        ...cosasHogar.map(({ tipo }) => tipo),
        ...accesoriosElectronicos.map(({ tipo }) => tipo),
        ...prendasHombre.map(({ tipo }) => tipo),
        ...prendasMujer.map(({ tipo }) => tipo)
    ])
];

// Agregar el parámetro 'e' para representar el evento
navLateral.addEventListener('click', e => {
    if (e.target.classList.contains('nav-buscar')) {
        const idNav = e.target.getAttribute('id');
        const tipoSeleccionado = tipoArrays.find(tipo => tipo === idNav);
        if (tipoSeleccionado) {
        mostrarBusquedaNav(tipoSeleccionado);
        }
    }
});

function mostrarBusquedaNav(tipo) {
    resultadosBusqueda.innerHTML = ''; // Limpiar los resultados anteriores
    const productosEncontrados = todosLosProductos.filter(producto => producto.tipo.toLowerCase() === tipo.toLowerCase());

    productosEncontrados.forEach(producto => {
        const { nombre, precio, imagen } = producto;
        const cardHTML = `
        <div class="card">
            <img src="${imagen}" id="imgCard" alt="Descripción de la imagen">
            <div class="contenido-card">
            <div class="medida-responsive">
                <h3>${nombre}</h3>
                <p>Precio: $ <span class="precio">${precio}</span></p>
            </div>
            <div class="btn-responsive">
                <img class="agregar" src="img/carrito de compras.png" title="agregar a carrito" >
                <button class="ver">Ver</button>
            </div>
            </div>
        </div>
        `;
        resultadosBusqueda.insertAdjacentHTML('beforeend', cardHTML);
});

    resultad.style.display = 'flex';
    hogar.style.display = 'none';
    electronico.style.display = 'none';
    ropa.style.display = 'none';
}
      
// Agregar eventos a la tienda y al carrito
tienda.addEventListener('click', (e) => {
    if (e.target.classList.contains('ver')) {
        const productoSeleccionado = e.target.closest('.card');
        leerProducto(productoSeleccionado);
    } else if (e.target.classList.contains('agregar')) {
        const productoCarrito = e.target.closest('.card');
        leerProductoCarrito(productoCarrito);

        numer += 1;
        incrementar();
    }
});

// tablecarrito.addEventListener('click', eliminarCurso);  //evento para eliminar cosas del carrito

// Función para leer y almacenar información del producto
function leerProducto(producto) {
    const imagen = producto.querySelector('img').src;
    const nombre = producto.querySelector('h3').textContent;
    const precio = producto.querySelector('.precio').textContent;
    const infoProducto = {
        imagen: imagen,
        nombre: nombre,
        precio: precio
    };

    localStorage.setItem('infoProducto', JSON.stringify(infoProducto));
    window.location.href = "Product.HTML";
}

// Función para agregar un producto al carrito
function leerProductoCarrito(car) {
    const infoCarrito = {
        imagen: car.querySelector('img').src,
        nombre: car.querySelector('h3').textContent,
        precio: car.querySelector('span').textContent,
        cantidad: 1
    };

    // Verificar si el elemento ya existe en el carrito
    const existe = articulosCarrito.some(car => car.nombre === infoCarrito.nombre);
    if (existe) {
        articulosCarrito = articulosCarrito.map(car => {
        if (car.nombre === infoCarrito.nombre) {
            car.cantidad++;
        }
        return car;
        });
    } else {
        articulosCarrito.push(infoCarrito);
    }

    crearCarrito();
}

// Función para eliminar un curso del carrito
// function eliminarCurso(e) {
//   if (e.target.classList.contains('borrar-curso')) {
//     const productoName = e.target.getAttribute('h3');
//     articulosCarrito = articulosCarrito.filter((car) => car.nombre == productoName);
//     crearCarrito();
//   }
// }

// Función para crear el contenido del carrito en la interfaz
function crearCarrito() {
    limpiarHTML();

    articulosCarrito.forEach((car) => {
        const { imagen, nombre, precio, cantidad} = car;
        const newTabla = document.createElement('tr');
        newTabla.innerHTML = `
        <td><img src="${imagen}" class="img-carrito"></td>
        <td>${nombre}</td>
        <td>${cantidad}</td>
        <td class="precio">$${precio}</td>
        `;
        // <td class="th-eliminar"><a href="#" class="borrar-curso" id="${nombre}"> x </a></td>

        tbcarrito.appendChild(newTabla);
    });
}

incrementar();

function incrementar() {
    document.getElementById("counter").innerText = numer;
    const noHayNada = document.querySelector('.noHaynada');

    if (numer > 0) {
        document.getElementById("counter").style.display = "flex";
        tablecarrito.style.display = 'block';
        pagar.style.display = 'block';
        noHayNada.style.display = 'none';
    } else if (numer < 1) {
        tablecarrito.style.display = 'none';
        pagar.style.display = 'none';
        noHayNada.style.display = 'flex';
    }
}

// Función para limpiar el contenido del carrito en la interfaz
function limpiarHTML() {
    while (tbcarrito.firstChild) {
        tbcarrito.removeChild(tbcarrito.firstChild);
    }
}

// Evento para vaciar el carrito
vaciarCarrito.addEventListener('click', () => {
    articulosCarrito = [];

    carrito.style.display = 'none';

    limpiarHTML();

    numer = 0;
    incrementar();
});

pagar.addEventListener('click', e => {
    setTimeout(() => {
        traladarFactura()
    }, 300);
})

document.addEventListener('DOMContentLoaded', () => {
    crmDB();
})

function crmDB() {
    // Crear base de datos version 1.0
    let crmDB = window.indexedDB.open('crm', 1);

    // Si hay un error
    crmDB.onerror = function() {
        console.log('Hubo un error');
    }

    // Si se creo bien
    crmDB.onsuccess = function() {
        DB =crmDB.result;
    }

    // Configuracion de base de datos
    crmDB.onupgradeneeded = function(e) {
        const db = e.target.result;

        const objectStore = db.createObjectStore('crm', {
            keyPath: 'crm',
            autoIncrement: true
        });

        // Definir columnas
        objectStore.createIndex('nombre', 'nombre', { unique: false });
        objectStore.createIndex('tipo', 'tipo', { unique: false });
        objectStore.createIndex('precio', 'precio', { unique: false });
        objectStore.createIndex('cantidad', 'cantidad', { unique: false });
    }
}

function traladarFactura() {
    let transaction = DB.transaction(['crm'], 'readwrite');

    transaction.oncompete = function() {
        console.log('transaction completada')
    }

    transaction.onerror = function() {
        console.log('transaction error')
    }

    const objectStore = transaction.objectStore('crm');

    const infoTraladar = objectStore.add(articulosCarrito);

    console.log(infoTraladar)
    window.location.href = "Bill.HTML";
    limpiarHTML();
}



